ENV_URI: "https://127.0.0.1/x/123-456a-789b-487e-wer5s-258c6482p654/api/v2/metrics/ingest"
Api_Token: "dt0c01.<DYNATRACE_API_TOKEN>"
log_level: "DEBUG"  # Change to INFO/DEBUG for detailed logs
log_retention_days: 7  # Number of days to retain logs
# Define timeout options
connect_timeout: "10"  # Timeout for api call connection phase (in seconds)
max_time: "15"         # Timeout for api call the entire request (in seconds)

functions:
  function1:
    server: "<TARGET_SERVER_A_IP>"
    username: "<username>"
    bankname: "bankA"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankA/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankA/bc.txt"
  function2:
    server: "<TARGET_SERVER_B_IP>"
    username: "<username>"
    bankname: "bankB"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankB/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankB/bc.txt"
  function3:
    server: "<TARGET_SERVER_C_IP>"
    username: "<username>"
    bankname: "bankC"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankC/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankC/bc.txt"
  function4:
    server: "<TARGET_SERVER_D_IP>"
    username: "<username>"
    bankname: "bankD"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankD/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankD/bc.txt"
  function5:
    server: "<TARGET_SERVER_E_IP>"
    username: "<username>"
    bankname: "bankE"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankE/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankE/bc.txt"
  function6:
    server: "<TARGET_SERVER_F_IP>"
    username: "<username>"
    bankname: "bankF"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankF/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankF/bc.txt"
  function7:
    server: "<TARGET_SERVER_G_IP>"
    username: "<username>"
    bankname: "bankG"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankG/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankG/bc.txt"
  function8:
    server: "<TARGET_SERVER_H_IP>"
    username: "<username>"
    bankname: "bankH"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankH/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankH/bc.txt"
  function9:
    server: "<TARGET_SERVER_I_IP>"
    username: "<username>"
    bankname: "bankI"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankI/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankI/bc.txt"
  function10:
    server: "<TARGET_SERVER_J_IP>"
    username: "<username>"
    bankname: "bankJ"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankJ/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankJ/bc.txt"
  function11:
    server: "<TARGET_SERVER_K_IP>"
    username: "<username>"
    bankname: "bankK"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankK/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankK/bc.txt"
  function12:
    server: "<TARGET_SERVER_L_IP>"
    username: "<username>"
    bankname: "bankL"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankL/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankL/bc.txt"
  function13:
    server: "<TARGET_SERVER_M_IP>"
    username: "<username>"
    bankname: "bankM"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankM/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankM/bc.txt"
  function14:
    server: "<TARGET_SERVER_N_IP>"
    username: "<username>"
    bankname: "bankN"
    remote_input_file: "/opt/<username>/QUEUE_DEPTH_MONITORING_DT/bankN/bc.txt"
    local_file: "/opt/dynatrace/Custom_Monitoring/WHATSUP_MONITORING/outfile/bankN/bc.txt"
