ENV_URI: "https://127.0.0.1/x/123-456a-789b-487e-wer5s-258c6482p654/api/v2/metrics/ingest"
Api_Token: "dt0c01.<DYNATRACE_API_TOKEN>"
script_path: "/opt/<username>/PORT_MONITORING/ports_scan.sh"
log_level: "DEBUG"  # Change to INFO/DEBUG for detailed logs
log_retention_days: 7  # Number of days to retain logs

functions:
  function1:
    server: "<TARGET_SERVER_A_IP>"
    username: "<username>"
    bankname: "bankA"
    service1: "FUN1 SRV1"
    service1_pattern: "FUN1 SRV1 PTN1"
    service1_pattern2: "FUN1 SRV1 PTN2"
    service2: "FUN1 SRV2"
    service2_pattern: "SRV2 PTN1"
   service2_pattern2: "SRV2PTN2"
    service3: "SRV3"
    service3_pattern: "SRV3PTN1"
    service3_pattern2: "SRV3PTN12"
    service4: "SRV4"
    service4_pattern: "SRV4PTN1"
    service4_pattern2: "SRV4PTN2"
    service5: "SRV5"
    service5_pattern: "SRV5PTN1"
    service5_pattern2: "SRV5PTN2"
    service6: "SRV6"
    service6_pattern: "SRV6PTN1"
    service6_pattern2: "SRV6PTN2"
    service7: "SRV7"
    service7_pattern: "SRV7PTN1"
    service7_pattern2: "SRV7PTN2"
    service8: "SRV8"
    service8_pattern: "SRV8PTN1"
    service8_pattern2: "SRV8PTN2"
    service9: "SRV9"
    service9_pattern: "SRV9PTN1"
    service9_pattern2: "SRV9PTN2"
